// <auto-generated />
namespace DocShare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DBGenerate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBGenerate));
        
        string IMigrationMetadata.Id
        {
            get { return "201702141006137_DBGenerate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
